// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhbH5VHY6uD_nQVlO9ucVo5SOaN20o5HY',
    appId: '1:268735114777:web:ad8527319895654a314488',
    messagingSenderId: '268735114777',
    projectId: 'carretera-1c328',
    authDomain: 'carretera-1c328.firebaseapp.com',
    storageBucket: 'carretera-1c328.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnHr2BXqSz_mHiCBUUC9moKOQj4swXsl4',
    appId: '1:268735114777:android:66d6be2dbe961f0d314488',
    messagingSenderId: '268735114777',
    projectId: 'carretera-1c328',
    storageBucket: 'carretera-1c328.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Q7Jq_meK0b0v9s98jHVYDsU2I5T6kyg',
    appId: '1:268735114777:ios:7a1556f609a45083314488',
    messagingSenderId: '268735114777',
    projectId: 'carretera-1c328',
    storageBucket: 'carretera-1c328.firebasestorage.app',
    iosBundleId: 'com.example.carretera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Q7Jq_meK0b0v9s98jHVYDsU2I5T6kyg',
    appId: '1:268735114777:ios:7a1556f609a45083314488',
    messagingSenderId: '268735114777',
    projectId: 'carretera-1c328',
    storageBucket: 'carretera-1c328.firebasestorage.app',
    iosBundleId: 'com.example.carretera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhbH5VHY6uD_nQVlO9ucVo5SOaN20o5HY',
    appId: '1:268735114777:web:01c722e13ee93244314488',
    messagingSenderId: '268735114777',
    projectId: 'carretera-1c328',
    authDomain: 'carretera-1c328.firebaseapp.com',
    storageBucket: 'carretera-1c328.firebasestorage.app',
  );
}
